language: python
python:
- '2.7'
sudo: required
services:
- docker
install:
- docker pull kbase/kb-sdk
- docker run kbase/kb-sdk genscript > $HOME/bin/kb-sdk
- chmod 755 $HOME/bin/kb-sdk
- export PATH=$PATH:$HOME/bin/kb-sdk
- kb-sdk sdkbase
- kb-sdk test || true
- make build-test-script
- sed -i "s/test_token=/test_token=$TEST_TOKEN/" test_local/test.cfg
- sed -i "s/appdev.//" test_local/test.cfg
- sed -i 's/$(id -u)/0:0/' test_local/run_tests.sh
script:
- kb-sdk test
after_success:
- cp test_local/workdir/.coverage .
- sudo mkdir -p /kb/module/lib/
- sudo cp -R test_local/workdir/kb/module/lib/kb_deseq /kb/module/lib/
- coverage report -m
- coveralls
env:
  global:
    secure: aNRTcrOXiyGg3Q4S713O0IIgerCEbhi0fhYGZa2Yfl0J46W+hfcD8vPyeGedS1vNK/+vBjNToBsqFgCYpvhr6+b9q4TO9roc7ttVq3ABzsJZkox8qeZQ08X53xWCtk+BiBWuqADIJrZZLye8l+zeTZHPC6faWJqIWVeitlDFCGXWLJSP/d347EKYZcwB25aP1q+YpuMxL1HUWuOePwZMh32ik12k98uCgXiOZYRuzImdPnN1Gjhpe7V+PWd/Fwyx5k20IBJUly1ZBzT7pvurlmXLcHaO2VgLQbmSHJaIxqZfxKmS2I0xZBAVL60/d8asaAFsqSHxl0I/ZOVOPMo1CHgHXzV1Cg0Vj1bioStfvnEAhld+WhMbhIJ5pbbks7GMgvkYTdpGI5biVjEbD3KtzmSC3fVEGTknE9qxheKAabE8AYmSsrmT3xZDszQ/YAwrq4rHTciROme4f48m1SyptIKegh+y/32mT02A3fwUd6HI2svNr0HJONNM6Uw9AMV/gDY2lM4K03+xGxhNQjk3Z/UQ56ys0fVHgMR1Vjnope32Dofqf0lrZWJrcQ9LBneXpt3g86FWqkEjETZnRX8Y+z/I5OGtUOrwJ1R9S9c5Xy3crV3OPfxHZdAux2Qm5SH5Btkjjt2GM5ZbiXlFf9FRAZo8PBGZvjHXJvPFGEIaFpU=
